name: Deno CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno: ["v1.x"]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}

      - name: Lint Code
        run: deno lint

      - name: Check Code Format
        run: deno fmt --check

      - name: Run Tests
        run: deno task test
