name: Publish Binaries

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish binaries for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: sherlock-linux
          - os: windows-latest
            asset_name: sherlock-windows.exe
          - os: macos-latest
            asset_name: sherlock-macos

    steps:
    - uses: actions/checkout@v2

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: ${{ matrix.deno }}

    - name: Compile to binary
      run: deno compile --output=${{ matrix.asset_name }} -q --allow-net cli.ts

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.asset_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
